#ifndef __IDEVICEID_H
#define __IDEVICEID_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

#define IDeviceID_OP_readJtagID 0
#define IDeviceID_OP_readSerialNum 1
#define IDeviceID_OP_getDeviceUUID 2

static inline int32_t
IDeviceID_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IDeviceID_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IDeviceID_readJtagID(Object self, uint32_t *jtagId_ptr)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { jtagId_ptr, sizeof(uint32_t) };

  return Object_invoke(self, IDeviceID_OP_readJtagID, a, ObjectCounts_pack(0, 1, 0, 0));
}

static inline int32_t
IDeviceID_readSerialNum(Object self, uint64_t *serialNum_ptr)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { serialNum_ptr, sizeof(uint64_t) };

  return Object_invoke(self, IDeviceID_OP_readSerialNum, a, ObjectCounts_pack(0, 1, 0, 0));
}

static inline int32_t
IDeviceID_getDeviceUUID(Object self, void *uuid_ptr, size_t uuid_len, size_t *uuid_lenout)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { uuid_ptr, uuid_len * 1 };

  int32_t result = Object_invoke(self, IDeviceID_OP_getDeviceUUID, a, ObjectCounts_pack(0, 1, 0, 0));

  *uuid_lenout = a[0].b.size / 1;

  return result;
}


#endif /* __IDEVICEID_H */
