#ifndef __IUPTIME_H
#define __IUPTIME_H

// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

// Copyright (c) 2015 Qualcomm Technologies, Inc.  All Rights Reserved.

// Qualcomm Technologies Proprietary and Confidential.

/**
 * @brief Get up time from bootup in ms.
 *
 */

#define IUptime_OP_getUptime 0

static inline int32_t
IUptime_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IUptime_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IUptime_getUptime(Object self, uint64_t *upTime_ptr)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { upTime_ptr, sizeof(uint64_t) };

  return Object_invoke(self, IUptime_OP_getUptime, a, ObjectCounts_pack(0, 1, 0, 0));
}


#endif /* __IUPTIME_H */
